const PracticeExplanationData = Array.from([
  {
    id: "ddd4823663e5cb49",
    comment:
      "Shut up, Moron. Halo was even voted AND rated better then Half Life or Half life 2.",
    prediction_proba: 95.68,
    prediction_label: "Toxic",
    important_words: [
      { word: "Moron", weight: 0.7, label: "Toxic" },
      { word: "Shut", weight: 0.36, label: "Toxic" },
      { word: "better", weight: 0.21, label: "Non-toxic" },
      { word: "up", weight: 0.17, label: "Toxic" },
      { word: "AND", weight: 0.11, label: "Toxic" },
      { word: "even", weight: 0.09, label: "Toxic" },
      { word: "voted", weight: 0.05, label: "Non-toxic" },
      { word: "rated", weight: 0.025, label: "Toxic" },
      { word: "Halo", weight: 0.02, label: "Non-toxic" },
      { word: "then", weight: 0.01, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "ddd4823663e5cb42",
    comment: "I hate how you are so correct in this situation",
    prediction_proba: 95.68,
    prediction_label: "Toxic",
    important_words: [
      { word: "Moron", weight: 0.7, label: "Toxic" },
      { word: "Shut", weight: 0.36, label: "Toxic" },
      { word: "better", weight: 0.21, label: "Non-toxic" },
      { word: "up", weight: 0.17, label: "Toxic" },
      { word: "AND", weight: 0.11, label: "Toxic" },
      { word: "even", weight: 0.09, label: "Toxic" },
      { word: "voted", weight: 0.05, label: "Non-toxic" },
      { word: "rated", weight: 0.025, label: "Toxic" },
      { word: "Halo", weight: 0.02, label: "Non-toxic" },
      { word: "then", weight: 0.01, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "ddd4823663e5cb41",
    comment:
      "Shut up, Moron. Halo was even voted AND rated better then Half Life or Half life 2.",
    prediction_proba: 95.68,
    prediction_label: "Toxic",
    important_words: [
      { word: "Moron", weight: 0.7, label: "Toxic" },
      { word: "Shut", weight: 0.36, label: "Toxic" },
      { word: "better", weight: 0.21, label: "Non-toxic" },
      { word: "up", weight: 0.17, label: "Toxic" },
      { word: "AND", weight: 0.11, label: "Toxic" },
      { word: "even", weight: 0.09, label: "Toxic" },
      { word: "voted", weight: 0.05, label: "Non-toxic" },
      { word: "rated", weight: 0.025, label: "Toxic" },
      { word: "Halo", weight: 0.02, label: "Non-toxic" },
      { word: "then", weight: 0.01, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "7e9f81162b4dc973",
    comment:
      "You are rude, unprofessional, stupid and wasting my time. Scrap the article. Happy now?",
    prediction_proba: 98.64,
    prediction_label: "Toxic",
    new_important_words: [],
    important_words: [
      { word: "stupid", weight: 0.39, label: "Toxic" },
      { word: "You", weight: 0.15, label: "Toxic" },
      { word: "rude", weight: 0.13, label: "Toxic" },
      { word: "the", weight: 0.09, label: "Non-toxic" },
      { word: "article", weight: 0.09, label: "Toxic" },
      { word: "wasting", weight: 0.05, label: "Toxic" },
      { word: "Scrap", weight: 0.05, label: "Toxic" },
      { word: "Happy", weight: 0.04, label: "Non-toxic" },
      { word: "now", weight: 0.03, label: "Non-toxic" },
      { word: "my", weight: 0.02, label: "Non-toxic" },
    ],
    checked: false,
  },
]);
export default PracticeExplanationData;
