const TaskInterfaceExplanationData = Array.from([
  {
    id: "9da546936bcd59dc",
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Faucibus in ornare quam viverra orci sagittis eu volutpat odio.",
    prediction_proba: 86.32,
    prediction_label: "Toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "viverra", weight: 0.34, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "ornare", weight: 0.11, label: "Non-toxic" },
      { word: "incididunt", weight: 0.09, label: "Non-toxic" },
      { word: "sed", weight: 0.05, label: "Non-toxic" },
      { word: "aliqua", weight: 0.03, label: "Non-toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "Exercitation mollit aliquip duis deserunt ipsum ex et ex elit.",
    prediction_proba: 86.32,
    prediction_label: "Toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment:
      "Non commodo id pariatur id aliquip anim ad et ullamco id cillum fugiat ullamco.",
    prediction_proba: 86.32,
    prediction_label: "Non-toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment:
      "Nisi laborum cillum consequat velit cupidatat eiusmod non voluptate et labore cupidatat in.",
    prediction_proba: 86.32,
    prediction_label: "Toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "Dolore sit cillum do exercitation.",
    prediction_proba: 86.32,
    prediction_label: "Non-toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "Velit esse quis irure cupidatat.",
    prediction_proba: 86.32,
    prediction_label: "Non-toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "Non qui nulla deserunt deserunt minim cillum.",
    prediction_proba: 86.32,
    prediction_label: "Toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "Duis laborum irure consequat exercitation cillum.",
    prediction_proba: 86.32,
    prediction_label: "Toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
  {
    id: "9da546936bcd59dc",
    comment: "In in excepteur esse mollit sint aute in cillum.",
    prediction_proba: 86.32,
    prediction_label: "Non-toxic",
    important_words: [
      { word: "ipsum", weight: 0.72, label: "Toxic" },
      { word: "adipiscing", weight: 0.23, label: "Toxic" },
      { word: "sed", weight: 0.01, label: "Non-toxic" },
      { word: "tempor", weight: 0.61, label: "Non-toxic" },
      { word: "incididunt", weight: 0.02, label: "Non-toxic" },
      { word: "aliqua", weight: 0.0105, label: "Non-toxic" },
      { word: "ornare", weight: 0.0075, label: "Non-toxic" },
      { word: "viverra", weight: 0.0204, label: "Toxic" },
      { word: "sagittis", weight: 0.0158, label: "Non-toxic" },
      { word: "volutpat", weight: 0.0024, label: "Toxic" },
    ],
    checked: false,
  },
]);
export default TaskInterfaceExplanationData;
