const testList = Array.from([
  {
    id: "1",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "2",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "3",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "4",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "5",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "6",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "7",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "8",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "9",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "10",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "11",
    comment: "This is a test comment. Lets see what we say. Just random.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
  {
    id: "12",
    comment: "This is a test comment2. Lets see what we say. Just random2.",
    important_words: [
      { word: "VErylongword", weight: 8 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
      { word: "Love", weight: -3 },
      { word: "random", weight: 5 },
      { word: "Hate", weight: 2 },
    ],
  },
]);

export default testList;
